// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prospectus.Data;

namespace Prospectus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211008021925_addPlayerTableToDatabase")]
    partial class addPlayerTableToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prospectus.Models.Player", b =>
                {
                    b.Property<int>("player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("accuracy_percent")
                        .HasColumnType("int");

                    b.Property<int>("aimed_passes")
                        .HasColumnType("int");

                    b.Property<int>("attempts")
                        .HasColumnType("int");

                    b.Property<int>("avg_depth_of_target")
                        .HasColumnType("int");

                    b.Property<int>("avg_time_to_throw")
                        .HasColumnType("int");

                    b.Property<int>("bats")
                        .HasColumnType("int");

                    b.Property<int>("big_time_throws")
                        .HasColumnType("int");

                    b.Property<int>("btt_rate")
                        .HasColumnType("int");

                    b.Property<int>("completion_percent")
                        .HasColumnType("int");

                    b.Property<int>("completions")
                        .HasColumnType("int");

                    b.Property<int>("declined_penalties")
                        .HasColumnType("int");

                    b.Property<int>("def_gen_pressures")
                        .HasColumnType("int");

                    b.Property<int>("drop_rate")
                        .HasColumnType("int");

                    b.Property<int>("dropbacks")
                        .HasColumnType("int");

                    b.Property<int>("drops")
                        .HasColumnType("int");

                    b.Property<int>("first_downs")
                        .HasColumnType("int");

                    b.Property<int>("franchise_id")
                        .HasColumnType("int");

                    b.Property<int>("grades_hands_fumble")
                        .HasColumnType("int");

                    b.Property<int>("grades_offense")
                        .HasColumnType("int");

                    b.Property<int>("grades_pass")
                        .HasColumnType("int");

                    b.Property<int>("grades_run")
                        .HasColumnType("int");

                    b.Property<int>("hit_as_threw")
                        .HasColumnType("int");

                    b.Property<int>("interceptions")
                        .HasColumnType("int");

                    b.Property<int>("passing_snaps")
                        .HasColumnType("int");

                    b.Property<int>("penalties")
                        .HasColumnType("int");

                    b.Property<string>("player")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("player_game_count")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pressure_to_sack_rate")
                        .HasColumnType("int");

                    b.Property<int>("qb_rating")
                        .HasColumnType("int");

                    b.Property<int>("sack_percent")
                        .HasColumnType("int");

                    b.Property<int>("sacks")
                        .HasColumnType("int");

                    b.Property<int>("scrambles")
                        .HasColumnType("int");

                    b.Property<int>("spikes")
                        .HasColumnType("int");

                    b.Property<string>("team_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("thrown_aways")
                        .HasColumnType("int");

                    b.Property<int>("touchdowns")
                        .HasColumnType("int");

                    b.Property<int>("turnover_worthy_plays")
                        .HasColumnType("int");

                    b.Property<int>("twp_rate")
                        .HasColumnType("int");

                    b.Property<int>("yards")
                        .HasColumnType("int");

                    b.Property<int>("ypa")
                        .HasColumnType("int");

                    b.HasKey("player_id");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
